CREATE TABLE patients (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50),
  date_of_birth DATE,
  PRIMARY KEY (id)  
);

CREATE TABLE medical_histories (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  admitted_at TIMESTAMP,
  patient_id INT,
  status VARCHAR(50),
  PRIMARY KEY (id)  
);

CREATE TABLE invoices (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  total_amount DECIMAL(4,2),
  generated_at TIMESTAMP,
  payed_at TIMESTAMP,
  medical_history_id INT,
  PRIMARY KEY (id)  
);

CREATE TABLE invoice_items (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  unit_price DECIMAL(4,2),
  quantity INT,
  total_price DECIMAL(4,2),
  invoice_id INT,
  treatment_id INT,
  PRIMARY KEY (id)  
);

CREATE TABLE treatments (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(50),
  name VARCHAR(50),
  PRIMARY KEY (id)  
);

CREATE TABLE treatments_medical_histories (
  medical_histories_id INT,
  treatments_id INT,
  PRIMARY KEY (medical_histories_id, treatments_id)  
);

ALTER TABLE medical_histories
ADD CONSTRAINT fk_patient_id 
FOREIGN KEY (patient_id)
REFERENCES patients(id)
ON DELETE CASCADE;

ALTER TABLE treatments_medical_histories
ADD CONSTRAINT fk_medical_histories_id  
FOREIGN KEY (medical_histories_id)
REFERENCES medical_histories(id)
ON DELETE CASCADE;

ALTER TABLE treatments_medical_histories
ADD CONSTRAINT fk_treatments_id  
FOREIGN KEY (treatments_id)
REFERENCES treatments(id)
ON DELETE CASCADE;

ALTER TABLE invoice_items
ADD CONSTRAINT fk_invoice_id
FOREIGN KEY (invoice_id)
REFERENCES invoices(id)
ON DELETE CASCADE;

ALTER TABLE invoice_items
ADD CONSTRAINT fk_treatments_id 
FOREIGN KEY (treatments_id )
REFERENCES treatments(id)
ON DELETE CASCADE;

ALTER TABLE invoices
ADD CONSTRAINT fk_medical_histories_id
FOREIGN KEY (medical_histories_id )
REFERENCES medical_histories(id)
ON DELETE CASCADE;

CREATE INDEX patients_index ON medical_histories(patient_id);
CREATE INDEX medical_history_invoices_index ON invoices(medical_history_id);
CREATE INDEX invoices_index ON invoice_items(invoice_id);
CREATE INDEX treatments_invoice_items_index ON invoice_items(treatment_id);
CREATE INDEX medical_histories_index ON treatments_medical_histories(medical_histories_id);
CREATE INDEX treatments_index ON treatments_medical_histories(treatments_id);

